version: '3.8'

services:
  backend:
    build: .
    container_name: chat_api
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file:
      - .env  
    restart: always

  mongo:
    image: mongo:6.0
    container_name: chat_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
